colors:
  bright:
    black: '#282a40'
    blue: '#a3c5ff'
    cyan: '#98fffd'
    green: '#e0ffad'
    magenta: '#d6afed'
    red: '#eb7f84'
    white: '#d1e5ed'
    yellow: '#ffee7e'
  normal:
    black: '#181a29'
    blue: '#93bbff'
    cyan: '#98e4ff'
    green: '#cdea9f'
    magenta: '#d3a7ee'
    red: '#F07178'
    white: '#bfd5de'
    yellow: '#ffd47e'
  primary:
    background: '#0f101a'
    foreground: '#c5c9de'
font:
  bold:
    family: Hack NF
  italic:
    family: Hack NF
  normal:
    family: Hack NF
  size: 10.0
window:
  opacity: 0.85
  padding:
    x: 3
    y: 3
