#! /bin/sh

# kill programs
killall -q picom
killall -q sxhkd
killall -q polybar
killall -q xsetroot

#while pfrep -u $UID -x picom >/dev/null; do sleep 1; done
#while pfrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
#while pfrep -u $UID -x polybar >/dev/null; do sleep 1; done
#while pfrep -u $UID -x xsetroot >/dev/null; do sleep 1; done

# autostart apps
setxkbmap es &
nm-applet &
nitrogen --restore &
picom & 
sxhkd &
xsetroot -cursor_name left_ptr &
# borders
BW=2
WG=3

# colors
NORMAL_BORDER_COLOR="#3c3836"
ACTIVE_BORDER_COLOR="#ebdbb2"
FOCUSED_BORDER_COLOR="#d79921"
PRESEL_FEEDBACK_COLOR="#D6A36A"

~/.config/bspwm/launch-dual.sh
bspc monitor eDP-1 -d VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V
 
~/.config/polybar/launch.sh
#  bspc monitor -d I II III IV V 

bspc config border_width          $BW
bspc config window_gap            $WG
Bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$FOCUSED_BORDER_COLOR"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"

bspc config split_ratio           	   0.5
bspc config borderless_monocle     	   true
bspc config gapless_monocle       	   true
bspc config focus_follows_pointer 	   true
bspc config single_monocle        	   true
#bspc config focus_by_distance              true
bspc config history_aware_focus            true

